In [1]:
import pandas as pd
import numpy as np

username='sreyes'
header_occ=['code','username','name','password','email','occupation','gender','age']
header_int=['username','interest']
cdf = pd.read_csv('https://raw.githubusercontent.com/behminyan/IS470/master/client_newest.csv', usecols=[0,1,2,5], names=header_occ)
idf = pd.read_csv('https://raw.githubusercontent.com/behminyan/IS470/master/client_interest_newest.csv', names=header_int)

In [2]:
# print cdf.shape, idf.shape
# print cdf.occupation.unique(), len(cdf.occupation.unique())
# cdf.head(15)

In [3]:
interests = idf.interest.unique()
print interests, len(interests)

['Econometrics' 'Public Finance' 'Managerial Economics' 'Aerography'
 'Climate' 'Organizational Psychology' 'Strategic Management'
 'Graphic User Interface' 'Typography' 'Actuarial Science'
 'Stochastic Modelling' 'Computer Engineering' 'Pediatric Care'
 'Microbiology' 'Software Design' 'Nutrition' 'Human Resource'
 'Computer Systems' 'Healthcare Management' 'Patient Care' 'Marketing'
 'Consulting' 'Entrepreunership' 'Civil Engineering' 'Data Analytics'
 'Life Sciences' 'Financial Instruments' 'Marketing Strategy'
 'Financial Accounting' 'Corporate Governance' 'Corporate Finance'
 'Forensic Accounting' 'International Finance' 'Global Marketing'
 'Infomercials' 'Social Media Marketing' 'Advertising Strategy'
 'Search Engine Optimization' 'Experential Marketing' 'Aerodynamics'
 'Aeronautics' 'Mechatronics' 'Fluid Dynamics' 'Polymer Engineering'
 'Robotics' 'Cross-Breeding' 'Sustainable Farming' 'Molecular Biology'
 'Environmental Conservation' 'Plant Biology' 'Computational Mechanics'
 'Microelectromechanical Systems' 'Multi-Scale Modelling'
 'Energy and Thermal Systems' 'Materials for Sustainability'
 'Nanotechnology' 'Industrial Architecture' 'Public Building Architecture'
 'Green Design' 'Interior Design' 'Compliance' 'Forensic Audit'
 'Information System Audit' 'Audit Risk' 'Food Production' 'Vaccination'
 'Waste Treatment' 'Biotechnology' 'Genomics'
 'Geographic Information Systems' 'Geospatial Database' 'Map Design'
 'Plastics Engineering' 'Biochemical Engineering' 'Material Sciences'
 'Chemical Reactor' 'Hydraulics' 'Structural Engineering'
 'Transport Engineering' 'Water Supply Distribution'
 'Information Technology Law' 'Insolvency Law' 'Insurance' 'Contract Law'
 'Environmental Law' 'Computer Networks' 'Cryptography'
 'Integrated Circuits' 'Mobile Computing' 'Information Protection'
 'Operating Systems' 'Speech Processing' 'Cloud Computing' 'Logistics'
 'Customer Service' 'Negotiation' 'Postioning and Messaging Consulting'
 'Equity and Trust' 'Ethics' 'European Union Law'
 'International Sale of Goods' 'Artificial Intelligence'
 'Database Management' 'Virtual Reality' 'Internet of Things'
 'Environmental Sustainability' 'Sustainable Development'
 'Molecular Genetics' 'Statistical Analysis' 'Preventive Healthcare'
 'Public Health' 'Sociology' 'Apparel Design' 'Pattern Making'
 'Textile Design' 'Fashion Jewellery Design' 'Textile Printing'
 'Creative Fundraising' 'Documentary Production'
 'Photographic and Film Narrative' 'Cinematography' 'Film Composing'
 'New Media Technologies' 'Film Marketing and Distribution' 'Biochemistry'
 'Food Packaging' 'Food Preservation' 'Food Science' 'Harvest Technology'
 'Accounting Ethics' 'Accounting Information Systems' 'Corporate Tax'
 'Analytical Chemistry' 'Pharmacology' 'Mineralogy' 'Geochemistry'
 'Geophysics' 'Structural Geology' 'Engineering Geology'
 'Geohazards and Risk Analysis' 'Marine and Tectonics' 'Cryosphere'
 'Polar and Plenatary' 'Geo-environmental Engineering'
 'Marine Geotechnical Engineering' 'Graphic Design'
 'Interactive Visualization' 'Antitrust Law' 'Medical Malpractice'
 'Design Thinking' 'Innovative Design' 'Product Design'
 'Systems and Service Design' 'Architectural Design' 'Integration Systems'
 'Business Analytics' 'Embedded Systems' 'Computational Photography'
 'Documentary' 'Photography' 'Civil Law' 'Company Law' 'Comparative Law'
 'Government Contracts' 'Partnership Law' 'Patent Law' 'Restitution'
 'Corporate Finance Law' 'Consumer Protection' 'Literature' 'Fashion'
 'Marine Science' 'Oceanography' 'Aquatic Disease and Immunity'
 'Coastal Economies' 'Coastal Pollution' 'Market Sizing'
 'Business Marketing' 'Social Responsibility' 'Sustainable Marketing'
 'Packaging' 'Biomedical Science' 'Defence Materials' 'Green Technology'
 'Additive Manufacturing' 'Drug Safety' 'Hydrometeorology'
 'Meterological Consulting' 'Weather Forecasting' 'Data Visualization'
 'New Media Art' 'Drug Legislation and Safety' 'Landscape Photography'
 'Portrait Photography' 'Journalism' 'Sports Photography' 'Public Policy'
 'Economic Analysis' 'Music Business Operations' 'Music Marketing'
 'Music Production' 'Songwriting' 'Screenwriting' 'Playwriting'
 'Costume Design' 'Lighting Design' 'Production Design' 'Scenic Design'
 'Audio Engineering' 'Acoustics' 'Demography' 'Medical Statistics'
 'Network Security' 'Electronic Switching Systems' 'Fibre Optics'
 'Systems Engineering' 'Terrestrial Radio Link Systems' 'Game Design'] 218

In [4]:
# http://stackoverflow.com/questions/27298178/concatenate-strings-from-several-rows-using-pandas-groupby
idf['compiled_int'] = idf[['username','interest']].groupby(['username'])['interest'].transform(lambda x: ', '.join(x))
# del idf['interest']

# # http://stackoverflow.com/questions/23667369/drop-all-duplicate-rows-in-python-pandas
idf.drop_duplicates(subset=['username'], keep='last', inplace=True)
# print idf.shape
idf.head(10)

,username,interest,compiled_int
2,dlarson,Managerial Economics,"Econometrics, Public Finance, Managerial Econo..."
4,kkennedy,Climate,"Aerography, Climate"
7,brogers,Managerial Economics,"Organizational Psychology, Strategic Managemen..."
8,nbarrett,Public Finance,Public Finance
10,brose,Typography,"Graphic User Interface, Typography"
12,rrichardson,Stochastic Modelling,"Actuarial Science, Stochastic Modelling"
13,sfrench,Organizational Psychology,Organizational Psychology
14,kcraig,Strategic Management,Strategic Management
15,dstone,Computer Engineering,Computer Engineering
16,jsummers,Pediatric Care,Pediatric Care

In [5]:
result = pd.merge(cdf, idf[['username','compiled_int']], how='left', on=['username'])
result.head()

,code,username,name,occupation,compiled_int
0,GV0CP,sadkins,Santiago Adkins,Anesthesiologist,"Healthcare Management, Patient Care"
1,MFOY4,nbarrett,Nancy Barrett,Financial Advisor,Public Finance
2,68UWE,tbates,Tricia Bates,Property Manager,"Consulting, Strategic Management"
3,M1F0S,wbishop,Winifred Bishop,Management consultant,"Consulting, Strategic Management"
4,BQF12,rbridges,Rafael Bridges,Business Development Manager,"Consulting, Marketing, Strategic Management"

In [6]:
# http://stackoverflow.com/questions/18658106/quick-implementation-of-character-n-grams-using-python
def get_ngrams(phr,n=3):
    #ensure length of word > n, else return entire word
    if len(phr)<=n:
        return [phr]
    ngrams = [phr[i:i+n] for i in range(len(phr)-n+1)]
#     print ngrams
    return ngrams

# http://stackoverflow.com/questions/22428020/how-to-extract-character-ngram-from-sentences-python
# import re
# def get_ngrams2(phr):
#     ngrams = re.findall(r'(?=(...))',phr)
#     print ngrams

In [7]:
from collections import Counter

# unused. focus on exists (1/0) vs 'count'

# http://stackoverflow.com/questions/722697/best-way-to-turn-word-list-into-frequency-dict
# http://stackoverflow.com/questions/893417/item-frequency-count-in-python # defaultdict, Counter(list)
# def count_ngrams(phr,n):
#     ngrams = get_ngrams(phr,n)
#     c=Counter()
#     for i in ngrams:
#         c[i] += 1
#     print c

In [8]:
result['occupation_v'] = [get_ngrams(occ) for occ in result.occupation]
result['int_v'] = [get_ngrams(compint) for compint in result.compiled_int]
result.head()

,code,username,name,occupation,compiled_int,occupation_v,int_v
0,GV0CP,sadkins,Santiago Adkins,Anesthesiologist,"Healthcare Management, Patient Care","[Ane, nes, est, sth, the, hes, esi, sio, iol, ...","[Hea, eal, alt, lth, thc, hca, car, are, re , ..."
1,MFOY4,nbarrett,Nancy Barrett,Financial Advisor,Public Finance,"[Fin, ina, nan, anc, nci, cia, ial, al , l A, ...","[Pub, ubl, bli, lic, ic , c F, Fi, Fin, ina, ..."
2,68UWE,tbates,Tricia Bates,Property Manager,"Consulting, Strategic Management","[Pro, rop, ope, per, ert, rty, ty , y M, Ma, ...","[Con, ons, nsu, sul, ult, lti, tin, ing, ng,, ..."
3,M1F0S,wbishop,Winifred Bishop,Management consultant,"Consulting, Strategic Management","[Man, ana, nag, age, gem, eme, men, ent, nt , ...","[Con, ons, nsu, sul, ult, lti, tin, ing, ng,, ..."
4,BQF12,rbridges,Rafael Bridges,Business Development Manager,"Consulting, Marketing, Strategic Management","[Bus, usi, sin, ine, nes, ess, ss , s D, De, ...","[Con, ons, nsu, sul, ult, lti, tin, ing, ng,, ..."

In [9]:
# count_ngrams("Econometrics",3)
# get_ngrams("Managerial Economics",3)

In [10]:
print 'total ngrams to analyse:', str(len(result.occupation_v)), "occupations,", str(len(result.int_v)), "interests"

total ngrams to analyse: 500 occupations, 500 interests

In [11]:
#create list of all features
def get_list(col, n=60):
    c=Counter()
    FEATURES_NUM = n
    for string in col:
        ngrams = get_ngrams(string)
        for i in ngrams:
            c[i] += 1
    words = [word for word, count in c.most_common(FEATURES_NUM)]
    # words = sorted(c, key = c.get, reverse = True)[:FEATURES_NUM] #alternative
    tuple_counts = [tup for tup in c.most_common(FEATURES_NUM)]
    return words, tuple_counts

In [12]:
#making feature vector for every person
def get_vector(ngrams_user, ngrams_list):
    res_vector = []
    for k, ngram in enumerate(ngrams_list):
        res_vector.append(int(ngram in ngrams_user)) #convert boolean to int
    return res_vector

occ_ngrams, occ_counts = get_list(result.occupation)
print occ_ngrams
int_ngrams, int_counts = get_list(result.compiled_int)
print int_ngrams

# # test for one user
# ngram_user = get_ngrams("Consulting, Marketing, Strategic Management")
# arr = np.array(get_vector(ngram_user,int_ngrams)) 
# print arr

# get vectors for each user
user_vectors = [] # start with list, then convert to np array
vector = []
for i in range(len(result)):
    user_occ = get_vector(get_ngrams(result.occupation[i]),occ_ngrams)
    user_int = get_vector(get_ngrams(result.compiled_int[i]),int_ngrams)
    vector = np.concatenate((user_occ, user_int))
    user_vectors.append(vector)
user_vectors = np.asarray(user_vectors)

# print user_vectors[:3]

['ist', 'al ', 'ine', 'gin', 'nee', 'ngi', 'eer', 'eng', ' en', 'ogi', 'olo', 'gis', 'log', 'ent', 'ner', 'ica', 'ial', 'tor', 'cal', 'cia', 'tis', 'esi', 'des', 'sig', 'gne', ' de', 'ign', 'ana', 'nti', 'ien', 'cie', 'sci', 'l e', 'ech', ' sc', 'oun', 'ter', 'lis', 'yst', 'ali', 'edi', 'tan', 'rch', 'nta', 'tec', ' an', 'ani', 'ito', 'cou', 'unt', 'nic', 'cco', 'Acc', 'iol', 'eci', 'nag', 'pec', 'nal', 'age', 'ant']
['ing', 'al ', 'ion', 'ati', 's, ', 'tio', 'tin', ' Ma', 'ent', 'rat', 'ics', 'ic ', 'g, ', 'ng,', ' In', 'log', 'ate', 'olo', 'ial', ', M', 'nce', 'ogy', 'y, ', 'men', ' De', ', S', 'ine', 'e, ', 'sig', 'Des', 'ign', 'esi', 'ste', ' Co', 'Mar', 'tem', 'Sys', 'yst', ' Sy', 'anc', 'ter', 'ng ', 'ems', ', P', 'cs,', 'eti', 'eri', 'rke', ' La', 'ark', 'ket', 'n, ', 'ina', ', I', 'rin', 'Law', 'tic', 'ce,', 'gin', 'edi']

In [13]:
# Perform k-Means clustering
from sklearn.cluster import KMeans

print('Vectors created; clustering is starting now!')
X = pd.DataFrame(user_vectors)
CLUSTERS_COUNT = len(cdf)/10

km = KMeans(n_clusters=CLUSTERS_COUNT, random_state=1)
km.fit(X)
km.labels_
X['cluster'] = km.labels_
X.sort('cluster')
combined = pd.concat([X[['cluster']], result.drop(['name'],axis=1)], axis=1)
combined.sort_values(by='cluster').head(10)

Vectors created; clustering is starting now!

/Users/behminyan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:12: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

,cluster,code,username,occupation,compiled_int,occupation_v,int_v
130,0,02XJN,kweaver,Civil engineer,"Chemical Reactor, Fluid Dynamics, Hydraulics","[Civ, ivi, vil, il , l e, en, eng, ngi, gin, ...","[Che, hem, emi, mic, ica, cal, al , l R, Re, ..."
457,0,2.20E+15,lbryant,Sound engineer,"Acoustics, Music Business Operations, Songwriting","[Sou, oun, und, nd , d e, en, eng, ngi, gin, ...","[Aco, cou, ous, ust, sti, tic, ics, cs,, s, , ..."
303,0,JRTRZ,gmorton,IT systems test engineer,Computational Photography,"[IT , T s, sy, sys, yst, ste, tem, ems, ms , ...","[Com, omp, mpu, put, uta, tat, ati, tio, ion, ..."
305,0,K8IPR,krichardson,IT systems test engineer,"Cloud Computing, Computational Photography","[IT , T s, sy, sys, yst, ste, tem, ems, ms , ...","[Clo, lou, oud, ud , d C, Co, Com, omp, mpu, ..."
45,0,RJ28N,dstone,Computer Hardware Engineer,Computer Engineering,"[Com, omp, mpu, put, ute, ter, er , r H, Ha, ...","[Com, omp, mpu, put, ute, ter, er , r E, En, ..."
147,0,QDLQJ,ilewis,Computer engineer,"Cryptography, Integrated Circuits, Mobile Comp...","[Com, omp, mpu, put, ute, ter, er , r e, en, ...","[Cry, ryp, ypt, pto, tog, ogr, gra, rap, aph, ..."
146,0,5ROKV,kcox,Computer engineer,"Cloud Computing, Computer Networks, Robotics","[Com, omp, mpu, put, ute, ter, er , r e, en, ...","[Clo, lou, oud, ud , d C, Co, Com, omp, mpu, ..."
459,0,PH8CC,lhale,Sound engineer,Audio Engineering,"[Sou, oun, und, nd , d e, en, eng, ngi, gin, ...","[Aud, udi, dio, io , o E, En, Eng, ngi, gin, ..."
132,0,WRZX6,clpratt,Civil engineer,"Chemical Reactor, Hydraulics, Structural Engin...","[Civ, ivi, vil, il , l e, en, eng, ngi, gin, ...","[Che, hem, emi, mic, ica, cal, al , l R, Re, ..."
372,0,JQ9KG,msingleton,Materials engineer,Nanotechnology,"[Mat, ate, ter, eri, ria, ial, als, ls , s e, ...","[Nan, ano, not, ote, tec, ech, chn, hno, nol, ..."

In [16]:
X['cluster'] = km.labels_
X.sort('cluster')
comb = pd.concat([X, result.drop(['occupation_v','int_v'],axis=1)], axis=1)
present = comb.sort('cluster')[['cluster','name','occupation','compiled_int','username']]
present.head(40)

/Users/behminyan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app
/Users/behminyan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:4: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

,cluster,name,occupation,compiled_int,username
130,0,Kelly Weaver,Civil engineer,"Chemical Reactor, Fluid Dynamics, Hydraulics",kweaver
457,0,Lorraine Bryant,Sound engineer,"Acoustics, Music Business Operations, Songwriting",lbryant
303,0,Gregory Morton,IT systems test engineer,Computational Photography,gmorton
305,0,Kristy Richardson,IT systems test engineer,"Cloud Computing, Computational Photography",krichardson
45,0,Delbert Stone,Computer Hardware Engineer,Computer Engineering,dstone
147,0,Iris Lewis,Computer engineer,"Cryptography, Integrated Circuits, Mobile Comp...",ilewis
146,0,Kathy Cox,Computer engineer,"Cloud Computing, Computer Networks, Robotics",kcox
459,0,Lucy Hale,Sound engineer,Audio Engineering,lhale
132,0,Clarence Pratt,Civil engineer,"Chemical Reactor, Hydraulics, Structural Engin...",clpratt
372,0,Megan Singleton,Materials engineer,Nanotechnology,msingleton
127,0,Catherine Thompson,Civil engineer,"Fluid Dynamics, Transport Engineering",cthompson
460,0,Marta Mckinney,Sound engineer,Songwriting,mmckinney
351,1,Lydia Green,Marine biologist,"Coastal Pollution, Marine Science",lgreen
354,1,Norma Evans,Marine biologist,"Coastal Pollution, Oceanography",nevans
105,1,Brendan Murray,Biotechnologist,"Food Production, Vaccination, Waste Treatment",bmurray
415,1,Donald Wagner,Pharmacologist,"Biomedical Science, Drug Legislation and Safety",dwagner
100,1,Marian Perry,Biotechnologist,"Molecular Biology, Vaccination, Waste Treatment",mperry
99,1,Carole James,Biotechnologist,"Food Production, Waste Treatment",cjames
27,1,Jacob Mckinney,Psychologist,"Life Sciences, Organizational Psychology",jmckinney
414,1,Andrew Colon,Pharmacologist,"Biomedical Science, Drug Legislation and Safety",ancolon
419,1,Cecelia Henderson,Pharmacologist,Drug Legislation and Safety,chenderson
218,1,Rose Tran,Food technologist,"Food Packaging, Food Preservation, Food Science",rtran
224,1,Jean Morris,Food technologist,"Food Packaging, Food Preservation, Food Science",jmorris
221,1,Delbert Edwards,Food technologist,"Food Packaging, Food Preservation, Food Science",dedwards
13,1,Shelly French,Psychologist,Organizational Psychology,sfrench
196,2,Vanessa Johnston,Fashion designer,"Apparel Design, Fashion Jewellery Design, Text...",vjohnston
195,2,Ginger Rodriquez,Fashion designer,"Apparel Design, Fashion Jewellery Design, Text...",grodriquez
193,2,Ruth Ellis,Fashion designer,"Apparel Design, Fashion Jewellery Design, Text...",rellis
191,2,Eunice Tate,Fashion designer,"Fashion Jewellery Design, Textile Printing, Vi...",etate
451,2,Orville Brock,Set designer,"Lighting Design, Production Design, Scenic Design",obrock
454,2,Ramon Long,Set designer,"Costume Design, Lighting Design, Scenic Design",rlong
453,2,Kelly Hernandez,Set designer,"Lighting Design, Scenic Design",khernandez
452,2,Christopher Pratt,Set designer,"Costume Design, Lighting Design, Production De...",cpratt
337,3,Hope Rivera,Magazine editor,"Literature, Typography",hrivera
445,3,Geraldine Turner,Script editor,Screenwriting,gturner
339,3,Luz Underwood,Magazine editor,"Literature, Typography",lunderwood
444,3,Lester Beck,Script editor,Screenwriting,lbeck
443,3,Erick Gill,Script editor,Screenwriting,egill
442,3,Yvonne Washington,Script editor,Playwriting,ywashington
437,3,Thelma Hicks,Radio producer,Songwriting,thicks

In [17]:
target_cluster = combined[combined.username == username].iloc[0]['cluster']
# combined[combined.username == username]
present[present.cluster == target_cluster][present.username != username]

/Users/behminyan/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py:1997: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "DataFrame index.", UserWarning)

,cluster,name,occupation,compiled_int,username
161,39,Charles Ballard,Copywriter,"Advertising Strategy, Search Engine Optimizati...",cballard
58,39,Rita Barnes,Advertising specialist,"Advertising Strategy, Search Engine Optimizati...",rbarnes
57,39,Roderick Peterson,Advertising specialist,"Advertising Strategy, Infomercials, Search Eng...",rpeterson
158,39,Stuart Taylor,Copywriter,"Advertising Strategy, Search Engine Optimizati...",staylor
62,39,Stephen Ortiz,Advertising specialist,"Advertising Strategy, Infomercials, Social Med...",sortiz
60,39,Jake Cannon,Advertising specialist,"Advertising Strategy, Search Engine Optimizati...",jcannon